name: Deploy to registry

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy image
        uses: simons-containers/actions/deploy@main
        with:
          appname: glibc
          image_name: distroless-glibc
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          badges_token: ${{ secrets.GITHUB_TOKEN }}
          tag_latest: ${{ github.ref_name == github.event.repository.default_branch }}