name: Update versions

on:
  schedule:
    - cron: 0 11 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Fetch latest versions
        uses: nick-fields/retry@v4
        with:
          max_attempts: 5
          timeout_minutes: 10
          command: |
            set -uo pipefail
            GLIBC=$(curl -sf https://ftp.gnu.org/gnu/glibc/ \
              | grep -oP 'glibc-\K[0-9]+\.[0-9]+(?=\.tar\.xz)' \
              | sort -V | tail -1)
  
            TZDB=$(curl -sf https://data.iana.org/time-zones/tzdb/version)

            : ${GLIBC:?} ${TZDB:?}
  
            jq \
              --arg glibc "$GLIBC" \
              --arg tzdb  "$TZDB" \
              '
                .glibc   = $glibc |
                .tzdb    = $tzdb
              ' sources.json > tmp.json && mv tmp.json sources.json

            git diff sources.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: update-versions
          delete-branch: true
          title: Update versions
          commit-message: Update versions
